<<<<<<< HEAD
# Generated by Django 4.0.1 on 2022-02-15 05:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='account',
            new_name='calc',
        ),
    ]
=======
# Generated by Django 4.0.1 on 2022-02-15 05:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='account',
            new_name='calc',
        ),
    ]
>>>>>>> feff908ca3cc4f9fc888c5f3fcf21edaf7ac79b9
