<<<<<<< HEAD
# Generated by Django 4.0.1 on 2022-02-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_calc_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='calc',
            name='is_varified',
            field=models.BooleanField(default=False),
        ),
    ]
=======
# Generated by Django 4.0.1 on 2022-02-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_calc_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='calc',
            name='is_varified',
            field=models.BooleanField(default=False),
        ),
    ]
>>>>>>> feff908ca3cc4f9fc888c5f3fcf21edaf7ac79b9
